# Generated by Django 4.1.2 on 2022-10-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('allottedHours', models.IntegerField()),
            ],
        ),
    ]
