# Generated by Django 4.1.2 on 2022-10-14 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_group_task_project_group_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_manager_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
