# Generated by Django 4.1.2 on 2022-10-14 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_group_manager_alter_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('updated', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_samples', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='tracker.period')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='tracker.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
