services:
  web:
    restart: always
    environment:
      - HTTP_PORT
    build: ./web
    ports:
      - ${HTTP_PORT}:80
    links:
      - db:db
      - redis:redis
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000

  db:
    restart: always
    image: postgres:latest
    volumes:
      - webrdata:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redisdata:/data

volumes:
  webrdata:
  redisdata: